---
title: 'References'
teaching: 10
exercises: 2
---
# Books 

- Westfall, P. H., & Young, S. S. (1993). Resampling-based multiple testing: Examples and methods for p-value adjustment (Vol. 279). John Wiley & Sons.
- Hochberg, Y. (1987). Multiple comparison procedures. Wiley Series in Probability and Statistics.
- Dudoit, S., Van Der Laan, M. J., & van der Laan, M. J. (2008). Multiple testing procedures with applications to genomics (pp. XXXIII-588). New York: Springer.

# Articles

- Benjamini, Y., & Hochberg, Y. (1995). Controlling the false discovery rate: a practical and powerful approach to multiple testing. Journal of the Royal statistical society: series B (Methodological), 57(1), 289-300..
- Holm, S. (1979). A simple sequentially rejective multiple test procedure. Scandinavian journal of statistics, 65-70.
- Shaffer, J. P. (1995). Multiple hypothesis testing. Annual review of psychology, 46(1), 561-584.
- Storey, J. D., & Tibshirani, R. (2003). Statistical significance for genomewide studies. Proceedings of the National Academy of Sciences, 100(16), 9440-9445.
- Pollard, K. S., Dudoit, S., & van der Laan, M. J. (2005). Multiple testing procedures: the multtest package and applications to genomics. In Bioinformatics and computational biology solutions using R and bioconductor (pp. 249-271). New York, NY: Springer New York.

# Online Resources

- [Introduction to multiple testing]("https://biodatascience.github.io/compbio/test/multtest.html")

- [sgof: An R Package for Multiple Testing Problems]("https://journal.r-project.org/archive/2014/RJ-2014-027/RJ-2014-027.pdf")

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: instructor

Inline instructor notes can help inform instructors of timing challenges
associated with the lessons. They appear in the "Instructor View"

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
